### PR TITLE
Import Span from proc_macro2 instead of syn

### LINKED ISSUE #17: Cannot build: "cannot find export` in `syn
$ cargo build
```
Compiling enumset_derive v0.5.0 (/home/mrlogick/enumset/enumset_derive)
error[E0432]: unresolved import `syn::export`
  --> enumset_derive/src/lib.rs:10:10
   |
10 | use syn::export::Span;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by ocboogie**
Fixes #17

### CODE REVIEW

**Comment by hellow554** [comment]
ping @Lymia  this is somewhat critical and urgent. Can you please comment on this PR (merge it and release a new version hopefully? ;) )

**Comment by ocboogie** [comment]
I already commented this on #17, but I'm adding it here for more exposure. While we wait for a merge, as a temp fix, here's a patch you can add to your Cargo.toml:
```toml
[patch.crates-io.enumset_derive]
git = "https://github.com/ocboogie/enumset"
branch = "span-fix" 
```

**Comment by syrusakbary** [comment]
Would be awesome to get this merged soon, we are having some issues in Wasmer as well:

https://github.com/wasmerio/wasmer/issues/1986#issuecomment-755050725

**Comment by cpcloud** [comment]
@Lymia Any chance of getting this merged soon?

**Comment by syrusakbary** [comment]
This is blocking [Wasmer](https://github.com/wasmerio/wasmer) so we are thinking of using @ocboogie's fork and publishing it as a new crate as a way to allow people to use the latest version of Wasmer.

We'd love to use the official repo/crate, so please @Lymia let us know if you may be able to address it soon.

**Comment by syrusakbary** [comment]
We have created the `wasmer_enumset` crate with the fix if anyone is blocked on using a published crate.
https://crates.io/crates/wasmer_enumset

Looking forward to having the fix upstream 🤗

**Pull request merged**
